In [1]:
import scanpy as sc
import pickle as pk
import networkx as nx

### Read data

In [2]:
atac_train_path = 'data/atac-gex/paperdata/atac_train.h5ad'
atac_test_path = 'data/atac-gex/paperdata/atac_test.h5ad'
gex_train_path = 'data/atac-gex/paperdata/gex_train.h5ad'
gex_test_path = 'data/atac-gex/paperdata/gex_test.h5ad'

atac_train = sc.read_h5ad(atac_train_path)
atac_test = sc.read_h5ad(atac_test_path)
gex_train = sc.read_h5ad(gex_train_path)
gex_test = sc.read_h5ad(gex_test_path)

# # cái này chắc là do có trùng lặp trong dữ liệu atac 
# adata_atac.var_names_make_unique()
# adata_gex.var_names_make_unique()

In [5]:
gene_locus = pk.load(open('data/atac-gex/raw/gene locus 2.pkl', 'rb'))
gene_locus_int = pk.load(open('data/atac-gex/raw/gene locus int.pkl', 'rb'))
gene_locus

{'LINC01409': ['chr1-778276-779191'],
 'LINC01128': ['chr1-827067-827948',
  'chr1-838003-838737',
  'chr1-841079-841916',
  'chr1-842497-843414',
  'chr1-844132-844995',
  'chr1-857951-858596'],
 'NOC2L': ['chr1-958865-959755'],
 'KLHL17': ['chr1-960362-961092'],
 'ISG15': ['chr1-1013003-1013921'],
 'C1orf159': ['chr1-1098904-1099765',
  'chr1-1103977-1104847',
  'chr1-1115800-1116696'],
 'SDF4': ['chr1-1216767-1217568',
  'chr1-1219124-1219990',
  'chr1-1221799-1222650',
  'chr1-1231675-1232596'],
 'B3GALT6': ['chr1-1231675-1232596'],
 'UBE2J2': ['chr1-1259822-1260759',
  'chr1-1261922-1262753',
  'chr1-1264837-1265679',
  'chr1-1267340-1268176',
  'chr1-1273488-1274400'],
 'ACAP3': ['chr1-1291549-1292410',
  'chr1-1293405-1294303',
  'chr1-1305205-1306136',
  'chr1-1307807-1308738'],
 'INTS11': ['chr1-1324303-1325203'],
 'DVL1': ['chr1-1349039-1349947'],
 'AURKAIP1': ['chr1-1374956-1375847'],
 'CCNL2': ['chr1-1399018-1399920'],
 'MRPL20': ['chr1-1406892-1407778'],
 'ATAD3B': ['chr1-

In [7]:
gene_locus_int[19]

[]

In [6]:
max_len=0
for k, v in gene_locus_int.items():
    if max_len < len(v):
        max_len = len(v)
        max_key = k
max_len, max_key

(113, 4188)

In [8]:
len(gene_locus_int)

12348

In [9]:
from itertools import combinations
list(combinations(range(5),2))

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 3),
 (2, 4),
 (3, 4)]

In [8]:
temp = [50, 51, 52, 53, 54]
com = list(combinations(range(len(temp)),2))
for i,j in com:
    print(temp[i],temp[j])

50 51
50 52
50 53
50 54
51 52
51 53
51 54
52 53
52 54
53 54


In [9]:
gene_locus_int

{0: [0],
 1: [1, 2, 3, 4, 5, 6],
 2: [7],
 3: [8],
 4: [9],
 5: [10, 11, 12],
 6: [13, 14, 15, 16],
 7: [16],
 8: [17, 18, 19, 20, 21],
 9: [22, 23, 24, 25],
 10: [26],
 11: [27],
 12: [28],
 13: [29],
 14: [30],
 15: [31, 32, 33, 34],
 16: [35, 36],
 17: [37, 38],
 18: [39, 40],
 19: [],
 20: [41, 42, 43],
 21: [44, 45, 46, 47, 48, 49],
 22: [50, 51, 52, 53, 54],
 23: [55, 56, 57],
 24: [58, 59, 60, 61, 62, 63],
 25: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
 26: [81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100],
 27: [101, 102, 103, 104, 105],
 28: [106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121],
 29: [122, 123, 124],
 30: [124, 125],
 31: [126],
 32: [127, 128, 129, 130, 131, 132, 133, 134],
 33: [135, 136],
 34: [137, 138],
 35: [137, 138],
 36: [139],
 37: [140, 141, 142, 143, 144],
 38: [145, 146, 147, 148, 149, 150, 151,

In [11]:
for k, v in gene_locus_int.items():
    if len(v) > 0:
        combs = list(combinations(range(len(v)),2))
        for i,j in combs:
            print(v[i],v[j])
    if k > 10:
        break

1 2
1 3
1 4
1 5
1 6
2 3
2 4
2 5
2 6
3 4
3 5
3 6
4 5
4 6
5 6
10 11
10 12
11 12
13 14
13 15
13 16
14 15
14 16
15 16
17 18
17 19
17 20
17 21
18 19
18 20
18 21
19 20
19 21
20 21
22 23
22 24
22 25
23 24
23 25
24 25


In [13]:
atac_train_np = atac_train.X.toarray()
atac_train_np, atac_train_np.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (42492, 60263))

In [14]:
atac_test_np = atac_test.X.toarray()
atac_test_np, atac_test_np.shape

(array([[1., 1., 0., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (1000, 60263))

In [18]:
gex_train_np = gex_train.X.toarray()
gex_train_np, gex_train_np.shape

(array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.63566864],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 (42492, 12348))

In [16]:
gex_test_np = gex_test.X.toarray()
gex_test_np, gex_test_np.shape

(array([[0.       , 0.       , 0.       , ..., 0.       , 1.1290213,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ]], dtype=float32),
 (1000, 12348))

### Test with 1/100: train+val: 390, test: 10

#### txt file

##### graph_indicator

In [16]:
def save_graph_indicator(num_graphs, num_nodes,path='1_100/'):
    with open(path+'AG_graph_indicator.txt', 'w') as file:
        for i in range(num_graphs):
            for j in range(num_nodes):
                file.write(str(i+1))
                file.write('\n')

In [17]:
# save_graph_indicator(400,atac_train_np.shape[1])    # num_nodes:60263

##### Adjacency matrix

In [18]:
def save_adjacency_matrix(num_graphs, gen_locus_, path='1_100/'):
    with open(path+'AG_A.txt', 'w') as file:
        for i in range(num_graphs):
            for k, v in gene_locus_int.items():
                if len(v) > 0:
                    combs = list(combinations(range(len(v)),2))
                    for i,j in combs:
                        line1 = '\t' + str(v[i]) + ',\t' + str(v[j])
                        file.write(line1)
                        file.write('\n')
                        line2 = '\t' + str(v[j]) + ',\t' + str(v[i])
                        file.write(line2)
                        file.write('\n')

In [19]:
save_adjacency_matrix(1, gene_locus_int, 'format/')

In [ ]:
save_adjacency_matrix(400, gene_locus_int, 'format/')

#### directly

##### graph_indicator

In [10]:
def get_adj_list(gene_locus_):
    adj_list = []
    for k, v in gene_locus_int.items():
        if len(v) > 0:
            combs = list(combinations(range(len(v)),2))
            for i,j in combs:
                adj_list.append((v[i],v[j]))
        # if k>5:
        #     break
    return adj_list

In [22]:
get_adj_list(gene_locus_int)

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 5),
 (4, 6),
 (5, 6),
 (10, 11),
 (10, 12),
 (11, 12),
 (13, 14),
 (13, 15),
 (13, 16),
 (14, 15),
 (14, 16),
 (15, 16)]

In [11]:
def get_graph(num_nodes, gene_locus_, node_attributes, graph_labels):
    '''
        graph_labels: GEX vector
    '''
    node_list = list(range(num_nodes))
    G=nx.Graph()
    G.add_nodes_from(node_list)
    G.add_edges_from(get_adj_list(gene_locus_))
    for u in G.nodes:
        G.nodes[u]['feat'] = node_attributes[u]
    
    G.graph['feat_dim'] = 1
    G.graph['label'] = graph_labels
    return G

In [19]:
G = get_graph(atac_train_np.shape[1], gene_locus_int, atac_train_np[0,:], gex_train_np[0,:])
G

In [20]:
import matplotlib.pyplot as plt
nx.draw(G,with)
plt.show()

TypeError: '_AxesStack' object is not callable

<Figure size 432x288 with 0 Axes>