In [1]:
import scanpy as sc
import pickle as pk
import networkx as nx
import numpy as np
import random
from itertools import combinations

### Read data

In [2]:
atac_train_path = 'data/atac-gex/paperdata/atac_train.h5ad'
atac_test_path = 'data/atac-gex/paperdata/atac_test.h5ad'
gex_train_path = 'data/atac-gex/paperdata/gex_train.h5ad'
gex_test_path = 'data/atac-gex/paperdata/gex_test.h5ad'

atac_train = sc.read_h5ad(atac_train_path)
atac_test = sc.read_h5ad(atac_test_path)
gex_train = sc.read_h5ad(gex_train_path)
gex_test = sc.read_h5ad(gex_test_path)

# # cái này chắc là do có trùng lặp trong dữ liệu atac 
# adata_atac.var_names_make_unique()
# adata_gex.var_names_make_unique()

In [4]:
gene_locus = pk.load(open('data/atac-gex/raw/gene_locus.pkl', 'rb'))
gene_locus_int = pk.load(open('data/atac-gex/raw/gene_locus_int.pkl', 'rb'))
gene_locus

{'LINC01409': ['chr1-778276-779191'],
 'LINC01128': ['chr1-827067-827948',
  'chr1-838003-838737',
  'chr1-841079-841916',
  'chr1-842497-843414',
  'chr1-844132-844995',
  'chr1-857951-858596'],
 'NOC2L': ['chr1-958865-959755'],
 'KLHL17': ['chr1-960362-961092'],
 'ISG15': ['chr1-1013003-1013921'],
 'C1orf159': ['chr1-1098904-1099765',
  'chr1-1103977-1104847',
  'chr1-1115800-1116696'],
 'SDF4': ['chr1-1216767-1217568',
  'chr1-1219124-1219990',
  'chr1-1221799-1222650',
  'chr1-1231675-1232596'],
 'B3GALT6': ['chr1-1231675-1232596'],
 'UBE2J2': ['chr1-1259822-1260759',
  'chr1-1261922-1262753',
  'chr1-1264837-1265679',
  'chr1-1267340-1268176',
  'chr1-1273488-1274400'],
 'ACAP3': ['chr1-1291549-1292410',
  'chr1-1293405-1294303',
  'chr1-1305205-1306136',
  'chr1-1307807-1308738'],
 'INTS11': ['chr1-1324303-1325203'],
 'DVL1': ['chr1-1349039-1349947'],
 'AURKAIP1': ['chr1-1374956-1375847'],
 'CCNL2': ['chr1-1399018-1399920'],
 'MRPL20': ['chr1-1406892-1407778'],
 'ATAD3B': ['chr1-

In [5]:
gene_locus_int[19]

[41, 42, 43]

In [6]:
max_len=0
for k, v in gene_locus_int.items():
    if max_len < len(v):
        max_len = len(v)
        max_key = k
max_len, max_key

(62, 339)

In [7]:
len(gene_locus_int)

1235

In [8]:
from itertools import combinations
list(combinations(range(5),2))

[(0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 3),
 (2, 4),
 (3, 4)]

In [9]:
temp = [50, 51, 52, 53, 54]
com = list(combinations(range(len(temp)),2))
for i,j in com:
    print(temp[i],temp[j])

50 51
50 52
50 53
50 54
51 52
51 53
51 54
52 53
52 54
53 54


In [10]:
gene_locus_int

{0: [0],
 1: [1, 2, 3, 4, 5, 6],
 2: [7],
 3: [8],
 4: [9],
 5: [10, 11, 12],
 6: [13, 14, 15, 16],
 7: [16],
 8: [17, 18, 19, 20, 21],
 9: [22, 23, 24, 25],
 10: [26],
 11: [27],
 12: [28],
 13: [29],
 14: [30],
 15: [31, 32, 33, 34],
 16: [35, 36],
 17: [37, 38],
 18: [39, 40],
 19: [41, 42, 43],
 20: [44, 45, 46, 47, 48, 49],
 21: [50, 51, 52, 53, 54],
 22: [55, 56, 57],
 23: [58, 59, 60, 61, 62, 63],
 24: [64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
 25: [81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100],
 26: [101, 102, 103, 104, 105],
 27: [106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121],
 28: [122, 123, 124],
 29: [124, 125],
 30: [126],
 31: [127, 128, 129, 130, 131, 132, 133, 134],
 32: [135, 136],
 33: [137, 138],
 34: [137, 138],
 35: [139],
 36: [140, 141, 142, 143, 144],
 37: [145, 146, 147, 148, 149, 150, 151, 152, 153

In [11]:
for k, v in gene_locus_int.items():
    if len(v) > 0:
        combs = list(combinations(range(len(v)),2))
        for i,j in combs:
            print(v[i],v[j])
    if k > 10:
        break

1 2
1 3
1 4
1 5
1 6
2 3
2 4
2 5
2 6
3 4
3 5
3 6
4 5
4 6
5 6
10 11
10 12
11 12
13 14
13 15
13 16
14 15
14 16
15 16
17 18
17 19
17 20
17 21
18 19
18 20
18 21
19 20
19 21
20 21
22 23
22 24
22 25
23 24
23 25
24 25


In [12]:
atac_train_np = atac_train.X.toarray()
atac_train_np, atac_train_np.shape

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (42492, 60263))

In [13]:
atac_test_np = atac_test.X.toarray()
atac_test_np, atac_test_np.shape

(array([[1., 1., 0., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]], dtype=float32),
 (1000, 60263))

In [14]:
gex_train_np = gex_train.X.toarray()
gex_train_np, gex_train_np.shape

(array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.63566864],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 (42492, 12348))

In [15]:
gex_test_np = gex_test.X.toarray()
gex_test_np, gex_test_np.shape

(array([[0.       , 0.       , 0.       , ..., 0.       , 1.1290213,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ]], dtype=float32),
 (1000, 12348))

### Test with 1/100: train+val: 390, test: 10

#### txt file

##### graph_indicator

In [16]:
def save_graph_indicator(num_graphs, num_nodes,path='1_100/'):
    with open(path+'AG_graph_indicator.txt', 'w') as file:
        for i in range(num_graphs):
            for j in range(num_nodes):
                file.write(str(i+1))
                file.write('\n')

In [17]:
# save_graph_indicator(400,atac_train_np.shape[1])    # num_nodes:60263

##### Adjacency matrix

In [18]:
def save_adjacency_matrix(num_graphs, gen_locus_, path='1_100/'):
    with open(path+'AG_A.txt', 'w') as file:
        for i in range(num_graphs):
            for k, v in gene_locus_int.items():
                if len(v) > 0:
                    combs = list(combinations(range(len(v)),2))
                    for i,j in combs:
                        line1 = '\t' + str(v[i]) + ',\t' + str(v[j])
                        file.write(line1)
                        file.write('\n')
                        line2 = '\t' + str(v[j]) + ',\t' + str(v[i])
                        file.write(line2)
                        file.write('\n')

In [19]:
# save_adjacency_matrix(1, gene_locus_int, 'format/')

In [20]:
# save_adjacency_matrix(400, gene_locus_int, 'format/')

#### directly

##### graph_indicator

In [21]:
def get_adj_list(gene_locus_):
    adj_list = []
    for k, v in gene_locus_int.items():
        if len(v) > 0:
            combs = list(combinations(range(len(v)),2))
            for i,j in combs:
                adj_list.append((v[i],v[j]))
        # if k>5:
        #     break
    return adj_list

In [22]:
get_adj_list(gene_locus_int)

[(1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (3, 4),
 (3, 5),
 (3, 6),
 (4, 5),
 (4, 6),
 (5, 6),
 (10, 11),
 (10, 12),
 (11, 12),
 (13, 14),
 (13, 15),
 (13, 16),
 (14, 15),
 (14, 16),
 (15, 16),
 (17, 18),
 (17, 19),
 (17, 20),
 (17, 21),
 (18, 19),
 (18, 20),
 (18, 21),
 (19, 20),
 (19, 21),
 (20, 21),
 (22, 23),
 (22, 24),
 (22, 25),
 (23, 24),
 (23, 25),
 (24, 25),
 (31, 32),
 (31, 33),
 (31, 34),
 (32, 33),
 (32, 34),
 (33, 34),
 (35, 36),
 (37, 38),
 (39, 40),
 (41, 42),
 (41, 43),
 (42, 43),
 (44, 45),
 (44, 46),
 (44, 47),
 (44, 48),
 (44, 49),
 (45, 46),
 (45, 47),
 (45, 48),
 (45, 49),
 (46, 47),
 (46, 48),
 (46, 49),
 (47, 48),
 (47, 49),
 (48, 49),
 (50, 51),
 (50, 52),
 (50, 53),
 (50, 54),
 (51, 52),
 (51, 53),
 (51, 54),
 (52, 53),
 (52, 54),
 (53, 54),
 (55, 56),
 (55, 57),
 (56, 57),
 (58, 59),
 (58, 60),
 (58, 61),
 (58, 62),
 (58, 63),
 (59, 60),
 (59, 61),
 (59, 62),
 (59, 63),
 (60, 61),
 (60, 62),
 (60, 63),
 (61, 62),
 (61, 6

In [23]:
def get_graph(num_nodes, gene_locus_, node_attributes, graph_labels):
    '''
        graph_labels: GEX vector
    '''
    node_list = list(range(num_nodes))
    G=nx.Graph()
    G.add_nodes_from(node_list)
    G.add_edges_from(get_adj_list(gene_locus_))
    for u in G.nodes:
        G.nodes[u]['feat'] = node_attributes[u]
    
    G.graph['feat_dim'] = 1
    G.graph['label'] = graph_labels
    return G

In [24]:
G = get_graph(atac_train_np.shape[1], gene_locus_int, atac_train_np[0,:], gex_train_np[0,:])
G

In [25]:
# import matplotlib.pyplot as plt
# nx.draw(G,with)
# plt.show()

SyntaxError: invalid syntax (762708302.py, line 2)

## Read group genes

In [44]:
group_genes = pk.load(open('data/atac-gex/raw/group_genes.pkl', 'rb'))
pw = pk.load(open('data/atac-gex/raw/pw.pkl', 'rb'))

In [28]:
group_genes

[['JUNB',
  'CXCL2',
  'ATF3',
  'NFKBIA',
  'TNFAIP3',
  'PTGS2',
  'CXCL1',
  'IER3',
  'CD83',
  'CCL20',
  'CXCL3',
  'MAFF',
  'NFKB2',
  'TNFAIP2',
  'HBEGF',
  'KLF6',
  'BIRC3',
  'PLAUR',
  'ZFP36',
  'ICAM1',
  'JUN',
  'EGR3',
  'IL1B',
  'BCL2A1',
  'PPP1R15A',
  'ZC3H12A',
  'SOD2',
  'NR4A2',
  'IL1A',
  'RELB',
  'TRAF1',
  'BTG2',
  'DUSP1',
  'MAP3K8',
  'ETS2',
  'F3',
  'SDC4',
  'EGR1',
  'IL6',
  'TNF',
  'KDM6B',
  'NFKB1',
  'LIF',
  'PTX3',
  'FOSL1',
  'NR4A1',
  'JAG1',
  'CCL4',
  'GCH1',
  'CCL2',
  'RCAN1',
  'DUSP2',
  'EHD1',
  'IER2',
  'REL',
  'CFLAR',
  'RIPK2',
  'NFKBIE',
  'NR4A3',
  'PHLDA1',
  'IER5',
  'TNFSF9',
  'GEM',
  'GADD45A',
  'CXCL10',
  'PLK2',
  'BHLHE40',
  'EGR2',
  'SOCS3',
  'SLC2A6',
  'PTGER4',
  'DUSP5',
  'SERPINB2',
  'NFIL3',
  'SERPINE1',
  'TRIB1',
  'TIPARP',
  'RELA',
  'BIRC2',
  'CXCL6',
  'LITAF',
  'TNFAIP6',
  'CD44',
  'INHBA',
  'PLAU',
  'MYC',
  'TNFRSF9',
  'SGK1',
  'TNIP1',
  'NAMPT',
  'FOSL2',
  'PNRC1',
 

In [30]:
list_genes = list(gene_locus.keys())
list_genes.index('LINC01409')

0

In [47]:
group1 = group_genes[2]
group1
ls_atac_indices = []
ls_gex_indices = []
atac_gex_dict = {}

list_genes = list(gene_locus.keys())
for gene in group1:
        if gene in list_genes:
            gene_id = list_genes.index(gene)
            atac_gex_dict[gene_id] = gene_locus_int[gene_id]
            for i in gene_locus_int[gene_id]:
                ls_atac_indices.append(i)
            ls_gex_indices.append(gene_id)
len(ls_atac_indices), len(ls_gex_indices)

(39, 9)

In [45]:
len(ls_atac_indices), len(ls_gex_indices)

(82, 16)

In [33]:
len(atac_gex_dict)

16

In [34]:
atac_gex_dict

{1066: [5023, 5024, 5025, 5026],
 972: [4482],
 448: [2268],
 305: [1626, 1627, 1628, 1629],
 1013: [4705],
 951: [4388, 4389],
 478: [2530, 2531],
 62: [258, 259, 260, 261, 262],
 311: [1641],
 1052: [4961],
 724: [3474],
 606: [3091, 3092],
 274: [1480, 1481, 1482, 1483, 1484, 1485],
 501: [2603, 2604],
 470: [2447,
  2448,
  2449,
  2450,
  2451,
  2452,
  2453,
  2454,
  2455,
  2456,
  2457,
  2458,
  2459,
  2460,
  2461,
  2462,
  2463,
  2464,
  2465,
  2466,
  2467,
  2468,
  2469,
  2470,
  2471,
  2472,
  2473,
  2474,
  2475,
  2476,
  2477,
  2478,
  2479,
  2480,
  2481,
  2482,
  2483,
  2484,
  2485,
  2486,
  2487],
 71: [358, 359, 360, 361, 362, 363, 364, 365]}

In [35]:
max_len=0
for k, v in atac_gex_dict.items():
    if max_len < len(v):
        max_len = len(v)
        max_key = k
max_len, max_key

(41, 470)

In [36]:
gene_locus

{'LINC01409': ['chr1-778276-779191'],
 'LINC01128': ['chr1-827067-827948',
  'chr1-838003-838737',
  'chr1-841079-841916',
  'chr1-842497-843414',
  'chr1-844132-844995',
  'chr1-857951-858596'],
 'NOC2L': ['chr1-958865-959755'],
 'KLHL17': ['chr1-960362-961092'],
 'ISG15': ['chr1-1013003-1013921'],
 'C1orf159': ['chr1-1098904-1099765',
  'chr1-1103977-1104847',
  'chr1-1115800-1116696'],
 'SDF4': ['chr1-1216767-1217568',
  'chr1-1219124-1219990',
  'chr1-1221799-1222650',
  'chr1-1231675-1232596'],
 'B3GALT6': ['chr1-1231675-1232596'],
 'UBE2J2': ['chr1-1259822-1260759',
  'chr1-1261922-1262753',
  'chr1-1264837-1265679',
  'chr1-1267340-1268176',
  'chr1-1273488-1274400'],
 'ACAP3': ['chr1-1291549-1292410',
  'chr1-1293405-1294303',
  'chr1-1305205-1306136',
  'chr1-1307807-1308738'],
 'INTS11': ['chr1-1324303-1325203'],
 'DVL1': ['chr1-1349039-1349947'],
 'AURKAIP1': ['chr1-1374956-1375847'],
 'CCNL2': ['chr1-1399018-1399920'],
 'MRPL20': ['chr1-1406892-1407778'],
 'ATAD3B': ['chr1-

In [51]:
ls_atac = []
num_atac=0
for k,i in (gene_locus_int.items()):
    num_atac += len(i)
    for j in i:
        ls_atac.append(j)
unique_atac = np.unique(np.array(ls_atac))
num_atac, unique_atac.shape

(6075, (5725,))

In [37]:
pw_np = np.array(pw)
pw_np.shape

(3, 741314)

In [38]:
pw_np[:,:10]

array([[1.05720000e+04, 1.05720000e+04, 1.05720000e+04, 1.05720000e+04,
        1.05720000e+04, 1.05720000e+04, 1.05720000e+04, 1.05720000e+04,
        1.05720000e+04, 1.05720000e+04],
       [3.00900000e+03, 1.10500000e+03, 8.16400000e+03, 4.41300000e+03,
        1.00900000e+03, 4.01400000e+03, 3.90500000e+03, 3.00800000e+03,
        1.18220000e+04, 6.37000000e+03],
       [7.45016670e-02, 1.93629105e-01, 5.64238500e-01, 5.96710616e-01,
        8.11767469e-02, 1.44067338e-01, 3.35810185e-01, 5.03219746e-02,
        1.37581372e-01, 2.03203187e-01]])

In [39]:
temp = pw_np[0,:]
ind = np.where(temp==10572)[0]
ind.shape, ind

((367,),
 array([     0,      1,      2,      3,      4,      5,      6,      7,
             8,      9,     10,     11,     12,     13,     14,     15,
            16,     17,     18,     19,     20,     21,     22,     23,
            24,     25,     26,     27,     28,     29,     30,     31,
            32,     33,     34,     35,     36,     37,     38,     39,
            40,     41,     42,     43,     44,     45,     46,     47,
            48,     49,     50,     51,     52,     53,     54,     55,
            56,     57,     58,     59,     60,     61,     62,     63,
            64,     65,     66,     67,     68,     69,     70,     71,
            72,     73,     74,     75,     76,     77,     78,     79,
            80,     81,     82,     83,     84,     85,     86,     87,
            88,     89,     90,     91,     92,     93,     94,     95,
            96,     97,     98,     99,    100,    101,    102,    103,
           104,    105,    106,    107,    108,    109,

In [40]:
pw_np[1,:][ind]

array([ 3009.,  1105.,  8164.,  4413.,  1009.,  4014.,  3905.,  3008.,
       11822.,  6370.,  8456.,  3668.,  6020.,  7008., 10905., 10842.,
       10500.,   457.,  5148.,  1691.,  8790., 10992.,   309.,  4491.,
        1776., 10926.,  5821.,  1051.,  3778.,  6109., 11590.,  3649.,
        4029.,  9527.,  3095.,  6842.,  7422., 11251.,  9703.,  8222.,
       11575.,  1606.,  6803., 10587.,  1464.,  1924.,  5323.,  4200.,
        5754.,  7567.,   987.,   489.,  3400.,  2102.,  6178., 10061.,
        5950.,  3356.,  6403., 10279.,  5698.,  5430.,  2670.,  6831.,
        7009.,  9011.,  6649.,  5437.,    63.,  4398.,  3724.,  4907.,
        1356.,  4281.,  1269.,  7250.,  3342.,  6032.,  9701.,   315.,
       11562.,  3837., 11527., 10372.,  1753.,  1090.,  7590.,   748.,
        4195.,  9623.,  4133.,  1792.,  6283.,  7045.,  3865.,  3610.,
        8339.,  7255.,  1305.,  3012.,  5714.,  5306.,  5775., 12010.,
         622.,  8027., 11460.,  6466.,  3215.,  2058.,  5378.,  4348.,
      

In [41]:
list_genes = list(gene_locus.keys())
num_neighbor = -1
source_ls = []
for gene in group1:
        if gene in list_genes:
            gene_id = list_genes.index(gene)
            temp = pw_np[0,:]
            ind = np.where(temp==gene_id)[0]
            if 0 < len(ind): 
                source_ls.append(gene_id)
            # for i in gene_locus_int[gene_id]:
            #     ls_atac_indices.append(i)
            # ls_gex_indices.append(gene_id)
len(source_ls), source_ls

(1, [1052])

In [42]:
atac_gex_dict

{1066: [5023, 5024, 5025, 5026],
 972: [4482],
 448: [2268],
 305: [1626, 1627, 1628, 1629],
 1013: [4705],
 951: [4388, 4389],
 478: [2530, 2531],
 62: [258, 259, 260, 261, 262],
 311: [1641],
 1052: [4961],
 724: [3474],
 606: [3091, 3092],
 274: [1480, 1481, 1482, 1483, 1484, 1485],
 501: [2603, 2604],
 470: [2447,
  2448,
  2449,
  2450,
  2451,
  2452,
  2453,
  2454,
  2455,
  2456,
  2457,
  2458,
  2459,
  2460,
  2461,
  2462,
  2463,
  2464,
  2465,
  2466,
  2467,
  2468,
  2469,
  2470,
  2471,
  2472,
  2473,
  2474,
  2475,
  2476,
  2477,
  2478,
  2479,
  2480,
  2481,
  2482,
  2483,
  2484,
  2485,
  2486,
  2487],
 71: [358, 359, 360, 361, 362, 363, 364, 365]}

In [43]:
ls_edge = []
combs_gene_pair = list(combinations(range(len(atac_gex_dict)),2))

for gene_id1, gene_id2 in combs_gene_pair:
    atac1 = atac_gex_dict[ls_gex_indices[gene_id1]]
    atac2 = atac_gex_dict[ls_gex_indices[gene_id2]]
    if len(atac1) > 0 and len(atac2) > 0:
        i = random.choice(atac1)
        j = random.choice(atac2)
        ls_edge.append((i,j))

ls_edge

[(5023, 4482),
 (5026, 2268),
 (5026, 1628),
 (5023, 4705),
 (5026, 4389),
 (5026, 2530),
 (5026, 261),
 (5025, 1641),
 (5023, 4961),
 (5026, 3474),
 (5026, 3091),
 (5023, 1484),
 (5025, 2604),
 (5023, 2447),
 (5025, 358),
 (4482, 2268),
 (4482, 1628),
 (4482, 4705),
 (4482, 4388),
 (4482, 2531),
 (4482, 261),
 (4482, 1641),
 (4482, 4961),
 (4482, 3474),
 (4482, 3091),
 (4482, 1484),
 (4482, 2604),
 (4482, 2470),
 (4482, 359),
 (2268, 1627),
 (2268, 4705),
 (2268, 4388),
 (2268, 2531),
 (2268, 258),
 (2268, 1641),
 (2268, 4961),
 (2268, 3474),
 (2268, 3092),
 (2268, 1484),
 (2268, 2603),
 (2268, 2487),
 (2268, 360),
 (1629, 4705),
 (1629, 4388),
 (1629, 2530),
 (1628, 258),
 (1626, 1641),
 (1629, 4961),
 (1629, 3474),
 (1626, 3092),
 (1629, 1481),
 (1627, 2603),
 (1626, 2486),
 (1628, 358),
 (4705, 4388),
 (4705, 2530),
 (4705, 258),
 (4705, 1641),
 (4705, 4961),
 (4705, 3474),
 (4705, 3091),
 (4705, 1483),
 (4705, 2604),
 (4705, 2474),
 (4705, 361),
 (4389, 2531),
 (4388, 261),
 (4388